In [2]:
from numpy import *

In [3]:
random.seed(42)
random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [4]:
arr= arange(0,25)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr= random.randint(0,101,10)

In [32]:
# max is for checking max number
ranarr.max()

99

In [34]:
# min is for checking min number index
ranarr.min()

2

In [35]:
# argmax is for checking max number index
ranarr.argmax()

5

In [36]:
# argmin is for checking min number index
ranarr.argmin()

7

In [38]:
ranarr.dtype

dtype('int32')

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.shape

(25,)

In [45]:
arr=arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)

In [17]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [1]:
from numpy import *

In [2]:
arr =arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5]=100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr=arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
sor=arr[0:5]

In [12]:
sor

array([0, 1, 2, 3, 4])

In [13]:
from numpy import *

In [14]:
array = arange(1,31)

In [15]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
arr=array.reshape(5,6)

In [17]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [18]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [19]:
arr[1]

array([ 7,  8,  9, 10, 11, 12])

In [20]:
arr[2]

array([13, 14, 15, 16, 17, 18])

In [21]:
arr[0,3]

4

In [22]:
arr[1,3]

10

In [23]:
arr[2,3]

16

In [24]:
arr[0:3,3]

array([ 4, 10, 16])

# slicing all the first inner arrays

In [28]:
arr[:2,1:]

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12]])

In [62]:
f=0.1
for n in range(1,100):
    print(f)
    f+=0.1

0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.2
1.3
1.4000000000000001
1.5000000000000002
1.6000000000000003
1.7000000000000004
1.8000000000000005
1.9000000000000006
2.0000000000000004
2.1000000000000005
2.2000000000000006
2.3000000000000007
2.400000000000001
2.500000000000001
2.600000000000001
2.700000000000001
2.800000000000001
2.9000000000000012
3.0000000000000013
3.1000000000000014
3.2000000000000015
3.3000000000000016
3.4000000000000017
3.5000000000000018
3.600000000000002
3.700000000000002
3.800000000000002
3.900000000000002
4.000000000000002
4.100000000000001
4.200000000000001
4.300000000000001
4.4
4.5
4.6
4.699999999999999
4.799999999999999
4.899999999999999
4.999999999999998
5.099999999999998
5.1999999999999975
5.299999999999997
5.399999999999997
5.4999999999999964
5.599999999999996
5.699999999999996
5.799999999999995
5.899999999999995
5.999999999999995
6.099999999999994
6.199999999999994
6.29999999999

In [36]:
(arange(-100, 0, 1)/100).reshape(10,10)
(arange(1,101)/100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [161]:
def avg(*tup):
    print(sum(tup)//len(tup))
avg(2,5,2,65,8)

16


In [206]:
array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09,
       0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18,
       0.19, 0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27,
       0.28, 0.29, 0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36,
       0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44, 0.45,
       0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63,
       0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 , 0.81,
       0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ,
       0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [150]:
tup=(2,5)

In [152]:
(tup[0]+tup[1])/len(tup)

3.5

In [154]:
sum(tup)/len(tup)

3.5

In [185]:
avg(7)

7.00


In [187]:
for i in f'fdjsfbdjsbf{123456}':
    print(i)

1


In [273]:
def avg(*tup):
    var=sum(tup)/len(tup)
#     print(var)
    print(int(f'%.2f' % var) + '\n')
nums = list(map(int, input().split()))
avg(*nums)

# def avg(*params):
#     var=sum(params)/len(params)
#     return f"{float(var):.2f}"
# avg([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
#         1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
#         0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
#        -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
#         1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

5
5.0


ValueError: invalid literal for int() with base 10: '5.00'

In [209]:
arr=[n for n in range(1,11)]

In [218]:
arr[0]%arr[0]*1

0

In [234]:
num=int(input(":-"))
def Febunacci(num):
    if num == 1:
        feb=[0]
    if num == 2:
        feb=[0,1]
    if num == 3:
        feb=[0,1,1]
    feb=[0,1,1]
    for n in range(1,num+1):
        feb.append(feb[-1]+feb[-2])
    print(feb)
Febunacci(num)

:-10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]


In [228]:
feb

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]

In [224]:
for n in range(1,16):
    if n%3==0 and n%5==0:
        print('FizzBuzz')
    elif n%5==0:
        print('Buzz')
    elif n%3==0:
        print('Fizz')
    else:
        print(n)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [243]:
range(1,(2-1)+1,(2-1))

range(1, 2)

In [242]:
range(0.01, (0.02-0.01)+1, (0.02-0.01))


TypeError: 'float' object cannot be interpreted as an integer

In [241]:
np.arange(0.01, (0.02-0.01)+1, (0.02-0.01)).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [245]:
print(f'{x:02})

SyntaxError: EOL while scanning string literal (540113983.py, line 1)

In [265]:
x=7.0
print(f"{x:.02}")

7.0


In [266]:
width=1.0
precision=1.0
f'{7:{width}.{precision}}' 

ValueError: Invalid format specifier

In [285]:
S = [1,2,3,4,5]
for index,item in enumerate(S):
#     print('s',s)
#     print('i',i)
    print(sum(S) - S[index])

14
13
12
11
10


In [289]:
def miniMaxSum(*arr):
    # Write your code here
    for index,item in enumerate(arr):
        ans=sum(arr) - arr[index]
    print(min(ans),max(ans))
miniMaxSum([7,69,2,221,8974])#[1,3,5,7,9])

299 9271


In [291]:
def NumOfPairs(colors):
    freq = {}
    for c in colors:
        freq[c] = freq.get(c, 0) + 1
        sum = 0
    for i in freq:
        if freq[i] > 1:
            sum += freq[i] // 2
    return f"Number of pairs: {sum}"
NumOfPairs([1,2,5,4,3,3,3,7])

'Number of pairs: 1'